//user
export const USER_AUTH = 'USER_AUTH';
export const USER_GET = 'USER_GET';
export const USER_LOGOUT = 'USER_LOGOUT';
export const REMOTE_USER_GET = 'REMOTE_USER_GET';
export const REMOTE_USER_FOLLOW_GET = 'REMOTE_USER_FOLLOW_GET';
export const KNACKSTEEM_USER_GET = 'KNACKSTEEM_USER_GET';

//articles
export const CATEGORIES_GET = 'CATEGORIES_GET';
export const ARTICLES_REQUEST = 'ARTICLES_REQUEST';
export const ARTICLES_GET = 'ARTICLES_GET';
export const ARTICLES_POSTING = 'ARTICLES_POSTING';
export const ARTICLES_POSTED = 'ARTICLES_POSTED';

//stats
export const USERLIST_REQUEST = 'USERLIST_REQUEST';
export const USERLIST_GET = 'USERLIST_GET';

//header
export const HEADER_VISIBILITY_SET = 'HEADER_VISIBILITY_SET';

export const STEEM_REWARD_FUND_GET = 'STEEM_REWARD_FUND_GET';
export const CURRENT_MEDIAN_HISTORY_PRICE_GET = 'CURRENT_MEDIAN_HISTORY_PRICE_GET';
export const DYNAMIC_GLOBAL_PROPERTIES_GET = 'DYNAMIC_GLOBAL_PROPERTIES_GET';

